apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dora-deployment
  name: dora-deployment
spec:
  selector:
    matchLabels:
      app: dora-deployment
  template:
    metadata:
      labels:
        app: dora-deployment
    spec:
      containers:
      - image: example:latest
        name: example
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8000

        livenessProbe:
          httpGet:
            path: /healthz
            port: http

