apiVersion: v1
kind: Service
metadata:
  labels:
    app: dora-deployment
  name: dora-deployment
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: dora-deployment
