name: compile-check-and-lint

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy -- -Dwarnings
      - run: cargo check --verbose
      - run: cargo test --verbose
